config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'registrations',
    :sessions => 'sessions'
}
  
  root 'home#index'
  resources :clothes, except: :index
  resources :users, only: [:show, :index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clothe.rb
class Clothe < ApplicationRecord
  mount_uploader :img, ImgUploader
  
  belongs_to :user
  validates :user_id, presence: true

  validates :memo, length: { maximum: 140 }

  def self.search(search)
    if search
      where(['item LIKE ? or color LIKE ?', "%#{search}%", "%#{search}%"])
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :clothes, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: { maximum: 50 }

  def feed
    Clothe.where("user_id = ?", id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_current_user

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  private
    def clothes_search_params
      params.require(:q).permit(:item_or_color_cont)
    end
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def show
    @clothe = Clothe.find(params[:id])
  end

  def new
    @clothe = Clothe.new
  end

  def create
    @clothe = current_user.clothes.create(clothe_params)
    if @clothe.save
      flash[:success] = "洋服を追加したよ！"
      redirect_to current_user
    else
      @clothe = []
      redirect_to current_user
    end
  end

  def edit
    @clothe = Clothe.find(params[:id])
  end

  def update
    @clothe = Clothe.find(params[:id])
    if @clothe.update(clothe_params)
      redirect_to current_user
    else
      redirect_to edit_clothe_path
    end
  end

  def destroy
    @clothe = Clothe.find(params[:id])
    @clothe.destroy
    flash[:success] = "洋服を削除したよ"
    redirect_to current_user
  end

  private
    def clothe_params
      params.require(:clothe).permit(:item, :color, :date, :memo, :img, :use_id)
    end

    def correct_user
      @clothe = current_user.clothes.find_by(id: params[:id])
      redirect_to root_url if @clothe.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  private
    def sign_up_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def account_up_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :destroy]
  before_action :admin_user, only: [:index, :destroy]

  def index
      @users= User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @clothes = @user.clothes.page(params[:page]).search(params[:search])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clothes/_clothes.html.erb
<div id="content">
  <% @clothes.each do |clothe| %>
    <div id="all_clothe_img" class="col-xs-3 col-md-2">
      <%= link_to clothe do %>
        <%= image_tag clothe.img.to_s, :size =>'90x120' %>
      <% end %>
    </div>
  <% end %>
</div>

<div id="paginate">
    <%= paginate @clothes %>
</div>

app/views/clothes/_form.html.erb
<%= form_with model: @clothe, locla:true do |f| %>
  <div class="form-group">
    <%= f.label :item %>
    <%= f.select :item, [["シャツ"], ["トップス"], ["パンツ"], ["スカート"], ["ワンピース"], ["その他"]], {}, class: 'form-control' %>
  </div><br>

  <div class="form-group">
    <%= f.label :color %>
    <%= f.select :color, [["青"], ["赤"], ["黄"], ["黒"], ["グレー"], ["白"], ["緑"], ["紫"], ["ピンク"], ["ベージュ"], ["ボーダー"], ["ストライプ"], ["水玉"], ["花柄"], ["その他"]], {}, class: 'form-control' %>
  </div><br>

  <%= f.label :data %>
  <div class='input-group date datepicker'>
    <%= f.text_field :date, class: 'form-control' %>
    <span class="input-group-addon"></span>
  </div><br>

  <div class="form-group">
    <%= f.label :memo %>
    <%= f.text_area :memo, class: 'form-control' %>
  </div><br>

  <div class="form-group">
    <%= f.label :img, :class => 'control-label' %>
    <%= f.file_field :img, id: :cloth_img %>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <p><%= f.check_box :remove_img %>画像を削除する</p><br>

  <div class="actions">
    <%= f.submit 'Post', class: "btn" %><br>
  </div>
<% end %>

app/views/clothes/edit.html.erb
<% provide(:title, "Edit Data") %>

<%= render 'form' %>

<div class="row">
  <div id="footer" class="col-xs-10 col-xs-offset-1">
    <ul class="nav nav-pills">
      <li role="presentation">
        <%= link_to 'My Closet', current_user %>
      </li>
      <li role="presentation">
        <%= link_to 'Back', :back %>
      </li>
    </ul>
  </div>
</div>

app/views/clothes/new.html.erb
<% provide(:title, "Add new clothe") %>

<%= render 'form' %>

<div class="row">
  <div id="footer" class="col-xs-10 col-xs-offset-1">
    <ul class="nav nav-pills">
      <li role="presentation">
        <%= link_to 'Back', :back %>
      </li>
    </ul>
  </div>
</div>

app/views/clothes/show.html.erb
<% provide(:title, "Clothe Data") %>

<div id="img">
    <%= image_tag @clothe.img.to_s, :size =>'100x130' if @clothe.img.present? %>
</div>

<div id="info">
  <h5><span class="under">Item & color</span></h5>
  <p><%= @clothe.item %> <%= @clothe.color %></p><br>
  <h5><span class="under">Date</span></h5>
  <p><%= @clothe.date %></p><br>
  <h5><span class="under">Memo</span></h5>
  <p><%= @clothe.memo %></p>
</div>

<div class="row">
  <div id="footer" class="col-xs-10 col-xs-offset-1">
    <ul class="nav nav-pills">
      <li role="presentation">
        <%= link_to 'Back', current_user %>
      </li>
      <li role="presentation">
        <%= link_to 'Edit', edit_clothe_path %>
      </li>
      <li role="presentation">
        <%= link_to 'Delete', @clothe, method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    </ul>
  </div>
</div>

app/views/home/index.html.erb
<div class="example">
  <div class="img">
    <%=image_tag "15334418751480.jpg" %>
  </div>
  <div class="text">
    <h1>Closet Application</h3>
  </div>
  <div class="msg">
    <% if user_signed_in? %>
      <p>Thank you for comming.</p>
    <% else %>
      <p>Welcome to our application</p><br>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <ul class="nav nav-tabs">
        <li role="presentation" class="active">
          <%= link_to "Home", root_path %>
        </li>
        <% if user_signed_in? %>
          <li role="presentation" class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">Menu <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li role="presentation">
                <%= link_to "My Closet", current_user %>
              </li>
              <li role="presentation">
                <%= link_to "Add New Closet", new_clothe_path%>
              </li>
              <li role="presentation">
                <%= link_to "Edit Your Data", edit_user_registration_path %>
              </li>
              <li role="presentation">
                <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
              </li>
              <% if current_user && current_user.admin? %>
                <li role="presentation">
                  <%= link_to "All Users", users_path %>
                </li>
              <% end %>
            </ul>
          </li>
        <% else %>
          <li role="presentation">
            <%= link_to "Sign in", new_user_session_path %>
          </li>
          <li role="presentation">
            <%= link_to "Sign up", new_user_registration_path %>
          </li>
        <% end %>
        <div class="page_title">
          <%= yield(:title) %>
        </div>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Closet Application</title>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= render 'layouts/shim' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <div class="small-body">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_clothes_search_form.html.erb
<%= form_tag current_user, :method => 'get' do %>
  <%= text_field_tag :search, params[:search], placeholder: "Input Item or color", :size=>"30" %>
    <%= submit_tag 'Search', :item => nil, :color => nil %>
<% end %>


app/views/users/index.html.erb
<% provide(:title, "All users") %>

<div id="users">
  <ul style="list-style:none;">
    <% @users.each do |user| %>
      <li>
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        <%= link_to user.name, user %>
        <% if current_user && current_user.admin? %> | <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
      </li><br>
    <% end %>
  </ul>

  <%= paginate @users %>

<div class="row">
  <div id="footer" class="col-xs-10 col-xs-offset-1">
    <ul class="nav nav-pills">
      <li role="presentation">
        <%= link_to 'Back', :back %>
      </li>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "My Closet") %>

<% if @user.clothes.none? %>
  <h4 class="message">No clothe here. Let's add clothes !</h4><br>
<% else %>
  <div class="row">
    <div id="search" class="col-xs-10 col-xs-offset-1">
      <%= render 'shared/clothes_search_form' %>
    </div>
  </div>
  <%= render 'clothes/clothes' %>
<% end %>

<div class="row">
  <div id="footer" class="col-xs-10 col-xs-offset-1">
    <ul class="nav nav-pills">
      <li role="presentation">
        <%= link_to 'Back', :back %>
      </li>
      <li role="presentation">
        <%= link_to 'Add New Clothe', new_clothe_path %>
      </li>
      <li role="presentation">
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      </li>
    </ul>
  </div>
</div>